"""Added created_by_id to grocery_store

Revision ID: 3bacfd35a5dc
Revises: 
Create Date: 2024-02-21 18:53:22.300353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bacfd35a5dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_groceryitem_user', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('grocery_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_groceryitem_user', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('grocery_store', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groceryitem_user', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groceryitem_user', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
